### ISSUE TITLE
Cannot get launcher to Load

### ISSUE THREAD

**Issue by rstuke82** [neatodev/BmLauncher#26]
I installed it by following the instructions, unblocked the app and when I go to launch the game nothing happens.  Running Windows 11 2H22.  The error below says windows users can ignore, but I don't see anything else causing this.  

`2022-10-23 10:26:11.4824|INFO|BmLauncherWForm.Program|Main - Starting logs at 10:26:11, on 23 October 2022.
2022-10-23 10:26:11.5229|DEBUG|BmLauncherWForm.Program|getResolutions - found a total of 9 available resolutions.
2022-10-23 10:26:11.6041|INFO|BmLauncherWForm.infrastructure.Factory|Constructor - Created Factory
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.infrastructure.Factory|setGPUName - found 2 Graphics Card(s). GPU selected: NVIDIA GeForce RTX 3050 Ti Laptop GPU
2022-10-23 10:26:11.6547|INFO|BmLauncherWForm.infrastructure.Factory|readConfigFile - processed BmEngine & UserEngine.
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized fullscreen as True
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized vsync as False
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized depth of field as True
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized ambient occlusion as True
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized lens flares as True
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized motion blur as False
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized bloom as True
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized dynamic shadows as True
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized disable spherical harmonic lights as False
2022-10-23 10:26:11.6547|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized fog volumes as True
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized distortion as True
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|init - initialized frame thread lag as True
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|initLang - initialized language as int
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|initAA - initialized multisampling as 1
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|initPhysx - initialized physx as 1
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|initAnisotropy - initialized max anisotropy as 4
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|initDetailmode - initialized detail mode as 2
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|initShadowTexels - initialized shadow depth bias as 0.012000
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|initShadowRes - initialized max shadow resolution as 1024
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|initLang - initialized framerate cap as 62.000000
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|initMemoryPoolsValue - initialized memory pools value as 1024
2022-10-23 10:26:11.6663|DEBUG|BmLauncherWForm.data.GuiInitializer|initResolutions - initialized resolution as 1280x720
2022-10-23 10:26:11.6663|WARN|BmLauncherWForm.data.WineChecker|IsWine - Wine not found. (Windows Users can ignore this.).
EntryPointNotFoundException: System.EntryPointNotFoundException: Unable to find an entry point named 'wine_get_version' in DLL 'ntdll.dll'.
   at BmLauncherWForm.data.WineChecker.GetWineVersion()
   at BmLauncherWForm.data.WineChecker.IsWine()
`

**Comment by neatodev** [comment]
Install/update NVIDIA drivers.

**Comment by rstuke82** [comment]
> Install/update NVIDIA drivers.

I am on the latest version.

**Comment by neatodev** [comment]
Then I need more info.
Is this the first launcher version that you're using or have you used older versions in the past? 
Since when is this issue happening?
Can you also please properly attach the log file in a comment?

**Comment by rstuke82** [comment]
ok I finally got it to work.  I went to grab a screenshot of my nvidia driver and it was asking me to install the driver again, even showed old version and new version as the same.  Ran thru a clean install, got a blue screen.  Used DDU and then reinstalled video driver again and it opens now.  Very strange.  Thanks for the quick responses.
